version: '3.7'
services:
    production:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=production
        logging:
            options:
                max-size: 10m
                max-file: '3'
        ports:
            - '5438:5432'
    test:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=test
        logging:
            options:
                max-size: 10m
                max-file: '3'
        ports:
            - '5436:5432'
